name: Prepare environment
description: Prepare the repository environment.

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store path
      id: pnpm
      run: |
        echo "::set-output name=store_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm.outputs.store_dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys:
          - ${{ runner.os }}-pnpm-

    - name: "Install dependencies"
      run: |
        pnpm install
