on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command:
          - tsc
          - eslint
          - prettier
      fail-fast: false

    steps:
      - uses: "./.github/actions/prepare-env"

      - run: pnpm lint:${{ matrix.command }}
