name: Testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare the repository environment
        uses: "./.github/actions/prepare-env"

      - run: pnpm test
